pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
               sh '../gradlew assembleRelease'
            }
        }
        stage('Archive') {
            steps {
                archiveArtifacts artifacts: '**/*.apk'
            }
        }
         stage('Logs') {
            steps {
                echo 'Do some shitty things' 
            }
        }

        // stage('Test') {
        //     steps {
        //         sh 'mvn test'
        //     }
        //     post {
        //         always {
        //             junit 'target/surefire-reports/*.xml'
        //         }
        //     }
        // }
         stage('Send Email') {
            steps {
                emailext body: 'The Android SDK has been built and attached to this email.',
                recipientList: ['ltdat@rogo.com.vn'],
                subject: 'Android SDK Build Complete',
                // attachments: [file: 'my-android-sdk.apk']
            }
        }
    }
}